name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
      release_type:
        description: "Release type"
        type: choice
        required: true
        options:
          - "release"
          - "alpha"
          - "beta"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      PACK_NAME: "Hana's Cobblemon Pack"
      MINECRAFT_VERSION: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packwiz
        uses: actionhippie/install-packwiz@v1

      # might just make this a python script instead of installing a whole binary
      - name: Setup python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.13"

      - name: Install toml-cli
        uses: baptiste0928/cargo-install@v3
        with:
          crate: toml-cli

      - name: Get Minecraft version
        run: |
          echo "MINECRAFT_VERSION=$(toml get pack.toml versions.minecraft | sed -e 's/^"//' -e 's/"$//')" >> $GITHUB_ENV

      - name: Set pack version
        run: |
          echo "$(toml set pack.toml version ${{ github.event.inputs.version }})" > pack.toml

      - name: Build pack
        run: python3 ./scripts/build.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: artifacts
          path: "*.mrpack"

      - name: Release to Modrinth & GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: htn7F7cq
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-tag: ${{ github.event.inputs.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-prerelease: ${{ github.event.inputs.release_type != 'release' }}

          name: ${{ env.PACK_NAME }} v${{ github.event.inputs.version }}
          version: ${{ github.event.inputs.version }}
          version-type: ${{ github.event.inputs.release_type }}
          game-versions: ${{ env.MINECRAFT_VERSION }}
          loaders: fabric

          files: "*.mrpack"
